server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://rm-uf6la91ia66461hdzxo.mysql.rds.aliyuncs.com:3306/bishe?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: hyl
    password: huyulong1999@
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**
logging:
  charset:
    console: utf-8
#  file:
#    name: springboot.log
#  level: error

